/*******************************************************************************
* File Name: cycfg_capsense_tuner_regmap.h
*
* Description:
* CAPSENSE Tuner register map configuration.
* This file should not be modified. It was automatically generated by
* CAPSENSE Configurator 6.10.0.3796
*
********************************************************************************
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company) 
* or an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_CAPSENSE_TUNER_REGMAP_H)
#define CYCFG_CAPSENSE_TUNER_REGMAP_H

/* RAM Data structure register definitions */
#define CY_CAPSENSE_TUNER_CONFIG_ID_OFFSET                                             (0u)
#define CY_CAPSENSE_TUNER_CONFIG_ID_SIZE                                               (2u)

#define CY_CAPSENSE_TUNER_TUNER_CMD_OFFSET                                             (2u)
#define CY_CAPSENSE_TUNER_TUNER_CMD_SIZE                                               (2u)

#define CY_CAPSENSE_TUNER_SCAN_COUNTER_OFFSET                                          (4u)
#define CY_CAPSENSE_TUNER_SCAN_COUNTER_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TUNER_ST_OFFSET                                              (6u)
#define CY_CAPSENSE_TUNER_TUNER_ST_SIZE                                                (1u)

#define CY_CAPSENSE_TUNER_INITDONE_OFFSET                                              (7u)
#define CY_CAPSENSE_TUNER_INITDONE_SIZE                                                (1u)

#define CY_CAPSENSE_TUNER_STATUS_OFFSET                                                (8u)
#define CY_CAPSENSE_TUNER_STATUS_SIZE                                                  (4u)

#define CY_CAPSENSE_TUNER_TIMESTAMPINTERVAL_OFFSET                                     (12u)
#define CY_CAPSENSE_TUNER_TIMESTAMPINTERVAL_SIZE                                       (4u)

#define CY_CAPSENSE_TUNER_TIMESTAMP_OFFSET                                             (16u)
#define CY_CAPSENSE_TUNER_TIMESTAMP_SIZE                                               (4u)

#define CY_CAPSENSE_TUNER_TUNER_CNT_OFFSET                                             (20u)
#define CY_CAPSENSE_TUNER_TUNER_CNT_SIZE                                               (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_FINGER_CP_OFFSET                                     (24u)
#define CY_CAPSENSE_TUNER_BUTTON0_FINGER_CP_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_SIGPFC_OFFSET                                        (26u)
#define CY_CAPSENSE_TUNER_BUTTON0_SIGPFC_SIZE                                          (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_MAX_RAW_COUNT_OFFSET                                 (28u)
#define CY_CAPSENSE_TUNER_BUTTON0_MAX_RAW_COUNT_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_ROW_MAX_RAW_COUNT_OFFSET                             (30u)
#define CY_CAPSENSE_TUNER_BUTTON0_ROW_MAX_RAW_COUNT_SIZE                               (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_FINGER_TH_OFFSET                                     (32u)
#define CY_CAPSENSE_TUNER_BUTTON0_FINGER_TH_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_PROX_TOUCH_TH_OFFSET                                 (34u)
#define CY_CAPSENSE_TUNER_BUTTON0_PROX_TOUCH_TH_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_LOW_BSLN_RST_OFFSET                                  (36u)
#define CY_CAPSENSE_TUNER_BUTTON0_LOW_BSLN_RST_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_SNS_CLK_OFFSET                                       (38u)
#define CY_CAPSENSE_TUNER_BUTTON0_SNS_CLK_SIZE                                         (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_ROW_SNS_CLK_OFFSET                                   (40u)
#define CY_CAPSENSE_TUNER_BUTTON0_ROW_SNS_CLK_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_GESTURE_DETECTED_OFFSET                              (42u)
#define CY_CAPSENSE_TUNER_BUTTON0_GESTURE_DETECTED_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_GESTURE_DIRECTION_OFFSET                             (44u)
#define CY_CAPSENSE_TUNER_BUTTON0_GESTURE_DIRECTION_SIZE                               (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_XDELTA_OFFSET                                        (46u)
#define CY_CAPSENSE_TUNER_BUTTON0_XDELTA_SIZE                                          (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_YDELTA_OFFSET                                        (48u)
#define CY_CAPSENSE_TUNER_BUTTON0_YDELTA_SIZE                                          (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_NOISE_TH_OFFSET                                      (50u)
#define CY_CAPSENSE_TUNER_BUTTON0_NOISE_TH_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_NNOISE_TH_OFFSET                                     (52u)
#define CY_CAPSENSE_TUNER_BUTTON0_NNOISE_TH_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_HYSTERESIS_OFFSET                                    (54u)
#define CY_CAPSENSE_TUNER_BUTTON0_HYSTERESIS_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_ON_DEBOUNCE_OFFSET                                   (56u)
#define CY_CAPSENSE_TUNER_BUTTON0_ON_DEBOUNCE_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_CLK_SOURCE_OFFSET                                    (57u)
#define CY_CAPSENSE_TUNER_BUTTON0_CLK_SOURCE_SIZE                                      (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_REGULAR_IIR_BL_N_OFFSET                              (58u)
#define CY_CAPSENSE_TUNER_BUTTON0_REGULAR_IIR_BL_N_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_STATUS_OFFSET                                        (59u)
#define CY_CAPSENSE_TUNER_BUTTON0_STATUS_SIZE                                          (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_PTRPOSITION_OFFSET                                   (60u)
#define CY_CAPSENSE_TUNER_BUTTON0_PTRPOSITION_SIZE                                     (4u)

#define CY_CAPSENSE_TUNER_BUTTON0_NUM_POSITIONS_OFFSET                                 (64u)
#define CY_CAPSENSE_TUNER_BUTTON0_NUM_POSITIONS_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_NUM_SUBCONVERSIONS_OFFSET                            (68u)
#define CY_CAPSENSE_TUNER_BUTTON0_NUM_SUBCONVERSIONS_SIZE                              (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_CDAC_REF0_OFFSET                                     (70u)
#define CY_CAPSENSE_TUNER_BUTTON0_CDAC_REF0_SIZE                                       (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_ROW_CDAC_REF0_OFFSET                                 (71u)
#define CY_CAPSENSE_TUNER_BUTTON0_ROW_CDAC_REF0_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_CIC_RATE_OFFSET                                      (72u)
#define CY_CAPSENSE_TUNER_BUTTON0_CIC_RATE_SIZE                                        (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_CDAC_DITHER_EN_OFFSET                                (73u)
#define CY_CAPSENSE_TUNER_BUTTON0_CDAC_DITHER_EN_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_CDAC_DITHER_VALUE_OFFSET                             (74u)
#define CY_CAPSENSE_TUNER_BUTTON0_CDAC_DITHER_VALUE_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_COARSE_INIT_BYPASS_EN_OFFSET                         (75u)
#define CY_CAPSENSE_TUNER_BUTTON0_COARSE_INIT_BYPASS_EN_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_COMP_DIV_OFFSET                                      (76u)
#define CY_CAPSENSE_TUNER_BUTTON0_COMP_DIV_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_LFSR_RANGE_OFFSET                                    (78u)
#define CY_CAPSENSE_TUNER_BUTTON0_LFSR_RANGE_SIZE                                      (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_FINGER_CP_OFFSET                                     (80u)
#define CY_CAPSENSE_TUNER_BUTTON1_FINGER_CP_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_SIGPFC_OFFSET                                        (82u)
#define CY_CAPSENSE_TUNER_BUTTON1_SIGPFC_SIZE                                          (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_MAX_RAW_COUNT_OFFSET                                 (84u)
#define CY_CAPSENSE_TUNER_BUTTON1_MAX_RAW_COUNT_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_ROW_MAX_RAW_COUNT_OFFSET                             (86u)
#define CY_CAPSENSE_TUNER_BUTTON1_ROW_MAX_RAW_COUNT_SIZE                               (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_FINGER_TH_OFFSET                                     (88u)
#define CY_CAPSENSE_TUNER_BUTTON1_FINGER_TH_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_PROX_TOUCH_TH_OFFSET                                 (90u)
#define CY_CAPSENSE_TUNER_BUTTON1_PROX_TOUCH_TH_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_LOW_BSLN_RST_OFFSET                                  (92u)
#define CY_CAPSENSE_TUNER_BUTTON1_LOW_BSLN_RST_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_SNS_CLK_OFFSET                                       (94u)
#define CY_CAPSENSE_TUNER_BUTTON1_SNS_CLK_SIZE                                         (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_ROW_SNS_CLK_OFFSET                                   (96u)
#define CY_CAPSENSE_TUNER_BUTTON1_ROW_SNS_CLK_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_GESTURE_DETECTED_OFFSET                              (98u)
#define CY_CAPSENSE_TUNER_BUTTON1_GESTURE_DETECTED_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_GESTURE_DIRECTION_OFFSET                             (100u)
#define CY_CAPSENSE_TUNER_BUTTON1_GESTURE_DIRECTION_SIZE                               (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_XDELTA_OFFSET                                        (102u)
#define CY_CAPSENSE_TUNER_BUTTON1_XDELTA_SIZE                                          (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_YDELTA_OFFSET                                        (104u)
#define CY_CAPSENSE_TUNER_BUTTON1_YDELTA_SIZE                                          (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_NOISE_TH_OFFSET                                      (106u)
#define CY_CAPSENSE_TUNER_BUTTON1_NOISE_TH_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_NNOISE_TH_OFFSET                                     (108u)
#define CY_CAPSENSE_TUNER_BUTTON1_NNOISE_TH_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_HYSTERESIS_OFFSET                                    (110u)
#define CY_CAPSENSE_TUNER_BUTTON1_HYSTERESIS_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_ON_DEBOUNCE_OFFSET                                   (112u)
#define CY_CAPSENSE_TUNER_BUTTON1_ON_DEBOUNCE_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_CLK_SOURCE_OFFSET                                    (113u)
#define CY_CAPSENSE_TUNER_BUTTON1_CLK_SOURCE_SIZE                                      (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_REGULAR_IIR_BL_N_OFFSET                              (114u)
#define CY_CAPSENSE_TUNER_BUTTON1_REGULAR_IIR_BL_N_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_STATUS_OFFSET                                        (115u)
#define CY_CAPSENSE_TUNER_BUTTON1_STATUS_SIZE                                          (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_PTRPOSITION_OFFSET                                   (116u)
#define CY_CAPSENSE_TUNER_BUTTON1_PTRPOSITION_SIZE                                     (4u)

#define CY_CAPSENSE_TUNER_BUTTON1_NUM_POSITIONS_OFFSET                                 (120u)
#define CY_CAPSENSE_TUNER_BUTTON1_NUM_POSITIONS_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_NUM_SUBCONVERSIONS_OFFSET                            (124u)
#define CY_CAPSENSE_TUNER_BUTTON1_NUM_SUBCONVERSIONS_SIZE                              (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_CDAC_REF0_OFFSET                                     (126u)
#define CY_CAPSENSE_TUNER_BUTTON1_CDAC_REF0_SIZE                                       (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_ROW_CDAC_REF0_OFFSET                                 (127u)
#define CY_CAPSENSE_TUNER_BUTTON1_ROW_CDAC_REF0_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_CIC_RATE_OFFSET                                      (128u)
#define CY_CAPSENSE_TUNER_BUTTON1_CIC_RATE_SIZE                                        (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_CDAC_DITHER_EN_OFFSET                                (129u)
#define CY_CAPSENSE_TUNER_BUTTON1_CDAC_DITHER_EN_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_CDAC_DITHER_VALUE_OFFSET                             (130u)
#define CY_CAPSENSE_TUNER_BUTTON1_CDAC_DITHER_VALUE_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_COARSE_INIT_BYPASS_EN_OFFSET                         (131u)
#define CY_CAPSENSE_TUNER_BUTTON1_COARSE_INIT_BYPASS_EN_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_COMP_DIV_OFFSET                                      (132u)
#define CY_CAPSENSE_TUNER_BUTTON1_COMP_DIV_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_LFSR_RANGE_OFFSET                                    (134u)
#define CY_CAPSENSE_TUNER_BUTTON1_LFSR_RANGE_SIZE                                      (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_FINGER_CP_OFFSET                                   (136u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_FINGER_CP_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_SIGPFC_OFFSET                                      (138u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_SIGPFC_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_MAX_RAW_COUNT_OFFSET                               (140u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_MAX_RAW_COUNT_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW_MAX_RAW_COUNT_OFFSET                           (142u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW_MAX_RAW_COUNT_SIZE                             (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_FINGER_TH_OFFSET                                   (144u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_FINGER_TH_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_PROX_TOUCH_TH_OFFSET                               (146u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_PROX_TOUCH_TH_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_LOW_BSLN_RST_OFFSET                                (148u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_LOW_BSLN_RST_SIZE                                  (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_SNS_CLK_OFFSET                                     (150u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_SNS_CLK_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW_SNS_CLK_OFFSET                                 (152u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW_SNS_CLK_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_GESTURE_DETECTED_OFFSET                            (154u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_GESTURE_DETECTED_SIZE                              (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_GESTURE_DIRECTION_OFFSET                           (156u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_GESTURE_DIRECTION_SIZE                             (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_XDELTA_OFFSET                                      (158u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_XDELTA_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_YDELTA_OFFSET                                      (160u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_YDELTA_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_NOISE_TH_OFFSET                                    (162u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_NOISE_TH_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_NNOISE_TH_OFFSET                                   (164u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_NNOISE_TH_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_HYSTERESIS_OFFSET                                  (166u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_HYSTERESIS_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ON_DEBOUNCE_OFFSET                                 (168u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ON_DEBOUNCE_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_CLK_SOURCE_OFFSET                                  (169u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_CLK_SOURCE_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_REGULAR_IIR_BL_N_OFFSET                            (170u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_REGULAR_IIR_BL_N_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_STATUS_OFFSET                                      (171u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_STATUS_SIZE                                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_PTRPOSITION_OFFSET                                 (172u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_PTRPOSITION_SIZE                                   (4u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_NUM_POSITIONS_OFFSET                               (176u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_NUM_POSITIONS_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_NUM_SUBCONVERSIONS_OFFSET                          (180u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_NUM_SUBCONVERSIONS_SIZE                            (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_CDAC_REF0_OFFSET                                   (182u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_CDAC_REF0_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW_CDAC_REF0_OFFSET                               (183u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW_CDAC_REF0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_CIC_RATE_OFFSET                                    (184u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_CIC_RATE_SIZE                                      (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_CDAC_DITHER_EN_OFFSET                              (185u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_CDAC_DITHER_EN_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_CDAC_DITHER_VALUE_OFFSET                           (186u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_CDAC_DITHER_VALUE_SIZE                             (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COARSE_INIT_BYPASS_EN_OFFSET                       (187u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COARSE_INIT_BYPASS_EN_SIZE                         (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COMP_DIV_OFFSET                                    (188u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COMP_DIV_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_LFSR_RANGE_OFFSET                                  (190u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_LFSR_RANGE_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_FINGER_CP_OFFSET                               (192u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_FINGER_CP_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SIGPFC_OFFSET                                  (194u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SIGPFC_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_MAX_RAW_COUNT_OFFSET                           (196u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_MAX_RAW_COUNT_SIZE                             (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ROW_MAX_RAW_COUNT_OFFSET                       (198u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ROW_MAX_RAW_COUNT_SIZE                         (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_FINGER_TH_OFFSET                               (200u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_FINGER_TH_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_PROX_TOUCH_TH_OFFSET                           (202u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_PROX_TOUCH_TH_SIZE                             (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_LOW_BSLN_RST_OFFSET                            (204u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_LOW_BSLN_RST_SIZE                              (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS_CLK_OFFSET                                 (206u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS_CLK_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ROW_SNS_CLK_OFFSET                             (208u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ROW_SNS_CLK_SIZE                               (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_GESTURE_DETECTED_OFFSET                        (210u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_GESTURE_DETECTED_SIZE                          (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_GESTURE_DIRECTION_OFFSET                       (212u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_GESTURE_DIRECTION_SIZE                         (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_XDELTA_OFFSET                                  (214u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_XDELTA_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_YDELTA_OFFSET                                  (216u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_YDELTA_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_NOISE_TH_OFFSET                                (218u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_NOISE_TH_SIZE                                  (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_NNOISE_TH_OFFSET                               (220u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_NNOISE_TH_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_HYSTERESIS_OFFSET                              (222u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_HYSTERESIS_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ON_DEBOUNCE_OFFSET                             (224u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ON_DEBOUNCE_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CLK_SOURCE_OFFSET                              (225u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CLK_SOURCE_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_REGULAR_IIR_BL_N_OFFSET                        (226u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_REGULAR_IIR_BL_N_SIZE                          (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_STATUS_OFFSET                                  (227u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_STATUS_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_PTRPOSITION_OFFSET                             (228u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_PTRPOSITION_SIZE                               (4u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_NUM_POSITIONS_OFFSET                           (232u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_NUM_POSITIONS_SIZE                             (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_NUM_SUBCONVERSIONS_OFFSET                      (236u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_NUM_SUBCONVERSIONS_SIZE                        (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CDAC_REF0_OFFSET                               (238u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CDAC_REF0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ROW_CDAC_REF0_OFFSET                           (239u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ROW_CDAC_REF0_SIZE                             (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CIC_RATE_OFFSET                                (240u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CIC_RATE_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CDAC_DITHER_EN_OFFSET                          (241u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CDAC_DITHER_EN_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CDAC_DITHER_VALUE_OFFSET                       (242u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_CDAC_DITHER_VALUE_SIZE                         (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_COARSE_INIT_BYPASS_EN_OFFSET                   (243u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_COARSE_INIT_BYPASS_EN_SIZE                     (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_COMP_DIV_OFFSET                                (244u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_COMP_DIV_SIZE                                  (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_LFSR_RANGE_OFFSET                              (246u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_LFSR_RANGE_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_RAW0_OFFSET                                     (248u)
#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_RAW0_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_BSLN0_OFFSET                                    (250u)
#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_BSLN0_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_DIFF0_OFFSET                                    (252u)
#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_DIFF0_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_STATUS0_OFFSET                                  (254u)
#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_STATUS0_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_NEG_BSLN_RST_CNT0_OFFSET                        (255u)
#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_NEG_BSLN_RST_CNT0_SIZE                          (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_BSLN_EXT0_OFFSET                                (256u)
#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_BSLN_EXT0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_CDAC_COMP0_OFFSET                               (257u)
#define CY_CAPSENSE_TUNER_BUTTON0_SNS0_CDAC_COMP0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_RAW0_OFFSET                                     (258u)
#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_RAW0_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_BSLN0_OFFSET                                    (260u)
#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_BSLN0_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_DIFF0_OFFSET                                    (262u)
#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_DIFF0_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_STATUS0_OFFSET                                  (264u)
#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_STATUS0_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_NEG_BSLN_RST_CNT0_OFFSET                        (265u)
#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_NEG_BSLN_RST_CNT0_SIZE                          (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_BSLN_EXT0_OFFSET                                (266u)
#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_BSLN_EXT0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_CDAC_COMP0_OFFSET                               (267u)
#define CY_CAPSENSE_TUNER_BUTTON1_SNS0_CDAC_COMP0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_RAW0_OFFSET                                   (268u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_BSLN0_OFFSET                                  (270u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_DIFF0_OFFSET                                  (272u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_STATUS0_OFFSET                                (274u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_NEG_BSLN_RST_CNT0_OFFSET                      (275u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_BSLN_EXT0_OFFSET                              (276u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_CDAC_COMP0_OFFSET                             (277u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL0_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_RAW0_OFFSET                                   (278u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_BSLN0_OFFSET                                  (280u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_DIFF0_OFFSET                                  (282u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_STATUS0_OFFSET                                (284u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_NEG_BSLN_RST_CNT0_OFFSET                      (285u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_BSLN_EXT0_OFFSET                              (286u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_CDAC_COMP0_OFFSET                             (287u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL1_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_RAW0_OFFSET                                   (288u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_BSLN0_OFFSET                                  (290u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_DIFF0_OFFSET                                  (292u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_STATUS0_OFFSET                                (294u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_NEG_BSLN_RST_CNT0_OFFSET                      (295u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_BSLN_EXT0_OFFSET                              (296u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_CDAC_COMP0_OFFSET                             (297u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL2_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_RAW0_OFFSET                                   (298u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_BSLN0_OFFSET                                  (300u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_DIFF0_OFFSET                                  (302u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_STATUS0_OFFSET                                (304u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_NEG_BSLN_RST_CNT0_OFFSET                      (305u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_BSLN_EXT0_OFFSET                              (306u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_CDAC_COMP0_OFFSET                             (307u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL3_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_RAW0_OFFSET                                   (308u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_BSLN0_OFFSET                                  (310u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_DIFF0_OFFSET                                  (312u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_STATUS0_OFFSET                                (314u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_NEG_BSLN_RST_CNT0_OFFSET                      (315u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_BSLN_EXT0_OFFSET                              (316u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_CDAC_COMP0_OFFSET                             (317u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL4_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_RAW0_OFFSET                                   (318u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_BSLN0_OFFSET                                  (320u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_DIFF0_OFFSET                                  (322u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_STATUS0_OFFSET                                (324u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_NEG_BSLN_RST_CNT0_OFFSET                      (325u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_BSLN_EXT0_OFFSET                              (326u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_CDAC_COMP0_OFFSET                             (327u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL5_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_RAW0_OFFSET                                   (328u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_BSLN0_OFFSET                                  (330u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_DIFF0_OFFSET                                  (332u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_STATUS0_OFFSET                                (334u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_NEG_BSLN_RST_CNT0_OFFSET                      (335u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_BSLN_EXT0_OFFSET                              (336u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_CDAC_COMP0_OFFSET                             (337u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL6_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_RAW0_OFFSET                                   (338u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_BSLN0_OFFSET                                  (340u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_DIFF0_OFFSET                                  (342u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_STATUS0_OFFSET                                (344u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_NEG_BSLN_RST_CNT0_OFFSET                      (345u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_BSLN_EXT0_OFFSET                              (346u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_CDAC_COMP0_OFFSET                             (347u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL7_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_RAW0_OFFSET                                   (348u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_BSLN0_OFFSET                                  (350u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_DIFF0_OFFSET                                  (352u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_STATUS0_OFFSET                                (354u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_NEG_BSLN_RST_CNT0_OFFSET                      (355u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_BSLN_EXT0_OFFSET                              (356u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_CDAC_COMP0_OFFSET                             (357u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL8_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_RAW0_OFFSET                                   (358u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_BSLN0_OFFSET                                  (360u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_DIFF0_OFFSET                                  (362u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_STATUS0_OFFSET                                (364u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_NEG_BSLN_RST_CNT0_OFFSET                      (365u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_BSLN_EXT0_OFFSET                              (366u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_CDAC_COMP0_OFFSET                             (367u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL9_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_RAW0_OFFSET                                  (368u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_BSLN0_OFFSET                                 (370u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_DIFF0_OFFSET                                 (372u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_STATUS0_OFFSET                               (374u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_NEG_BSLN_RST_CNT0_OFFSET                     (375u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_BSLN_EXT0_OFFSET                             (376u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_BSLN_EXT0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_CDAC_COMP0_OFFSET                            (377u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL10_CDAC_COMP0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_RAW0_OFFSET                                  (378u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_BSLN0_OFFSET                                 (380u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_DIFF0_OFFSET                                 (382u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_STATUS0_OFFSET                               (384u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_NEG_BSLN_RST_CNT0_OFFSET                     (385u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_BSLN_EXT0_OFFSET                             (386u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_BSLN_EXT0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_CDAC_COMP0_OFFSET                            (387u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL11_CDAC_COMP0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_RAW0_OFFSET                                  (388u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_BSLN0_OFFSET                                 (390u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_DIFF0_OFFSET                                 (392u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_STATUS0_OFFSET                               (394u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_NEG_BSLN_RST_CNT0_OFFSET                     (395u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_BSLN_EXT0_OFFSET                             (396u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_BSLN_EXT0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_CDAC_COMP0_OFFSET                            (397u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL12_CDAC_COMP0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_RAW0_OFFSET                                  (398u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_BSLN0_OFFSET                                 (400u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_DIFF0_OFFSET                                 (402u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_STATUS0_OFFSET                               (404u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_NEG_BSLN_RST_CNT0_OFFSET                     (405u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_BSLN_EXT0_OFFSET                             (406u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_BSLN_EXT0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_CDAC_COMP0_OFFSET                            (407u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL13_CDAC_COMP0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_RAW0_OFFSET                                  (408u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_BSLN0_OFFSET                                 (410u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_DIFF0_OFFSET                                 (412u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_STATUS0_OFFSET                               (414u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_NEG_BSLN_RST_CNT0_OFFSET                     (415u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_BSLN_EXT0_OFFSET                             (416u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_BSLN_EXT0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_CDAC_COMP0_OFFSET                            (417u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL14_CDAC_COMP0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_RAW0_OFFSET                                  (418u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_BSLN0_OFFSET                                 (420u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_DIFF0_OFFSET                                 (422u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_STATUS0_OFFSET                               (424u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_NEG_BSLN_RST_CNT0_OFFSET                     (425u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_BSLN_EXT0_OFFSET                             (426u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_BSLN_EXT0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_CDAC_COMP0_OFFSET                            (427u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_COL15_CDAC_COMP0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_RAW0_OFFSET                                   (428u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_BSLN0_OFFSET                                  (430u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_DIFF0_OFFSET                                  (432u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_STATUS0_OFFSET                                (434u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_NEG_BSLN_RST_CNT0_OFFSET                      (435u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_BSLN_EXT0_OFFSET                              (436u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_CDAC_COMP0_OFFSET                             (437u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW0_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_RAW0_OFFSET                                   (438u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_BSLN0_OFFSET                                  (440u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_DIFF0_OFFSET                                  (442u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_STATUS0_OFFSET                                (444u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_NEG_BSLN_RST_CNT0_OFFSET                      (445u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_BSLN_EXT0_OFFSET                              (446u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_CDAC_COMP0_OFFSET                             (447u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW1_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_RAW0_OFFSET                                   (448u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_BSLN0_OFFSET                                  (450u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_DIFF0_OFFSET                                  (452u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_STATUS0_OFFSET                                (454u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_NEG_BSLN_RST_CNT0_OFFSET                      (455u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_BSLN_EXT0_OFFSET                              (456u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_CDAC_COMP0_OFFSET                             (457u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW2_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_RAW0_OFFSET                                   (458u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_BSLN0_OFFSET                                  (460u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_DIFF0_OFFSET                                  (462u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_STATUS0_OFFSET                                (464u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_NEG_BSLN_RST_CNT0_OFFSET                      (465u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_BSLN_EXT0_OFFSET                              (466u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_CDAC_COMP0_OFFSET                             (467u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW3_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_RAW0_OFFSET                                   (468u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_BSLN0_OFFSET                                  (470u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_DIFF0_OFFSET                                  (472u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_STATUS0_OFFSET                                (474u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_NEG_BSLN_RST_CNT0_OFFSET                      (475u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_BSLN_EXT0_OFFSET                              (476u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_CDAC_COMP0_OFFSET                             (477u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW4_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_RAW0_OFFSET                                   (478u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_BSLN0_OFFSET                                  (480u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_DIFF0_OFFSET                                  (482u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_STATUS0_OFFSET                                (484u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_NEG_BSLN_RST_CNT0_OFFSET                      (485u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_BSLN_EXT0_OFFSET                              (486u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_CDAC_COMP0_OFFSET                             (487u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW5_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_RAW0_OFFSET                                   (488u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_BSLN0_OFFSET                                  (490u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_DIFF0_OFFSET                                  (492u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_STATUS0_OFFSET                                (494u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_NEG_BSLN_RST_CNT0_OFFSET                      (495u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_BSLN_EXT0_OFFSET                              (496u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_CDAC_COMP0_OFFSET                             (497u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW6_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_RAW0_OFFSET                                   (498u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_BSLN0_OFFSET                                  (500u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_DIFF0_OFFSET                                  (502u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_STATUS0_OFFSET                                (504u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_NEG_BSLN_RST_CNT0_OFFSET                      (505u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_BSLN_EXT0_OFFSET                              (506u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_CDAC_COMP0_OFFSET                             (507u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW7_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_RAW0_OFFSET                                   (508u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_BSLN0_OFFSET                                  (510u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_DIFF0_OFFSET                                  (512u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_STATUS0_OFFSET                                (514u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_NEG_BSLN_RST_CNT0_OFFSET                      (515u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_BSLN_EXT0_OFFSET                              (516u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_CDAC_COMP0_OFFSET                             (517u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW8_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_RAW0_OFFSET                                   (518u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_RAW0_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_BSLN0_OFFSET                                  (520u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_BSLN0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_DIFF0_OFFSET                                  (522u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_DIFF0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_STATUS0_OFFSET                                (524u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_STATUS0_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_NEG_BSLN_RST_CNT0_OFFSET                      (525u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_NEG_BSLN_RST_CNT0_SIZE                        (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_BSLN_EXT0_OFFSET                              (526u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_BSLN_EXT0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_CDAC_COMP0_OFFSET                             (527u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ROW9_CDAC_COMP0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_RAW0_OFFSET                               (528u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_RAW0_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_BSLN0_OFFSET                              (530u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_BSLN0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_DIFF0_OFFSET                              (532u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_DIFF0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_STATUS0_OFFSET                            (534u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_STATUS0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_NEG_BSLN_RST_CNT0_OFFSET                  (535u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_NEG_BSLN_RST_CNT0_SIZE                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_BSLN_EXT0_OFFSET                          (536u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_BSLN_EXT0_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_CDAC_COMP0_OFFSET                         (537u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS0_CDAC_COMP0_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_RAW0_OFFSET                               (538u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_RAW0_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_BSLN0_OFFSET                              (540u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_BSLN0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_DIFF0_OFFSET                              (542u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_DIFF0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_STATUS0_OFFSET                            (544u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_STATUS0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_NEG_BSLN_RST_CNT0_OFFSET                  (545u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_NEG_BSLN_RST_CNT0_SIZE                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_BSLN_EXT0_OFFSET                          (546u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_BSLN_EXT0_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_CDAC_COMP0_OFFSET                         (547u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS1_CDAC_COMP0_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_RAW0_OFFSET                               (548u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_RAW0_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_BSLN0_OFFSET                              (550u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_BSLN0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_DIFF0_OFFSET                              (552u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_DIFF0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_STATUS0_OFFSET                            (554u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_STATUS0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_NEG_BSLN_RST_CNT0_OFFSET                  (555u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_NEG_BSLN_RST_CNT0_SIZE                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_BSLN_EXT0_OFFSET                          (556u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_BSLN_EXT0_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_CDAC_COMP0_OFFSET                         (557u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS2_CDAC_COMP0_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_RAW0_OFFSET                               (558u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_RAW0_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_BSLN0_OFFSET                              (560u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_BSLN0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_DIFF0_OFFSET                              (562u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_DIFF0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_STATUS0_OFFSET                            (564u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_STATUS0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_NEG_BSLN_RST_CNT0_OFFSET                  (565u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_NEG_BSLN_RST_CNT0_SIZE                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_BSLN_EXT0_OFFSET                          (566u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_BSLN_EXT0_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_CDAC_COMP0_OFFSET                         (567u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS3_CDAC_COMP0_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_RAW0_OFFSET                               (568u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_RAW0_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_BSLN0_OFFSET                              (570u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_BSLN0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_DIFF0_OFFSET                              (572u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_DIFF0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_STATUS0_OFFSET                            (574u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_STATUS0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_NEG_BSLN_RST_CNT0_OFFSET                  (575u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_NEG_BSLN_RST_CNT0_SIZE                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_BSLN_EXT0_OFFSET                          (576u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_BSLN_EXT0_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_CDAC_COMP0_OFFSET                         (577u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS4_CDAC_COMP0_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_RAW0_OFFSET                               (578u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_RAW0_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_BSLN0_OFFSET                              (580u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_BSLN0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_DIFF0_OFFSET                              (582u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_DIFF0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_STATUS0_OFFSET                            (584u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_STATUS0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_NEG_BSLN_RST_CNT0_OFFSET                  (585u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_NEG_BSLN_RST_CNT0_SIZE                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_BSLN_EXT0_OFFSET                          (586u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_BSLN_EXT0_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_CDAC_COMP0_OFFSET                         (587u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS5_CDAC_COMP0_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_RAW0_OFFSET                               (588u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_RAW0_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_BSLN0_OFFSET                              (590u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_BSLN0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_DIFF0_OFFSET                              (592u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_DIFF0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_STATUS0_OFFSET                            (594u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_STATUS0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_NEG_BSLN_RST_CNT0_OFFSET                  (595u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_NEG_BSLN_RST_CNT0_SIZE                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_BSLN_EXT0_OFFSET                          (596u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_BSLN_EXT0_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_CDAC_COMP0_OFFSET                         (597u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS6_CDAC_COMP0_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_RAW0_OFFSET                               (598u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_RAW0_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_BSLN0_OFFSET                              (600u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_BSLN0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_DIFF0_OFFSET                              (602u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_DIFF0_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_STATUS0_OFFSET                            (604u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_STATUS0_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_NEG_BSLN_RST_CNT0_OFFSET                  (605u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_NEG_BSLN_RST_CNT0_SIZE                    (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_BSLN_EXT0_OFFSET                          (606u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_BSLN_EXT0_SIZE                            (1u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_CDAC_COMP0_OFFSET                         (607u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_SNS7_CDAC_COMP0_SIZE                           (1u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_X0_OFFSET                                          (608u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_X0_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_Y0_OFFSET                                          (610u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_Y0_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_Z0_OFFSET                                          (612u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_Z0_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ID0_OFFSET                                         (614u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ID0_SIZE                                           (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_X1_OFFSET                                          (616u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_X1_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_Y1_OFFSET                                          (618u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_Y1_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_Z1_OFFSET                                          (620u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_Z1_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TOUCHPAD0_ID1_OFFSET                                         (622u)
#define CY_CAPSENSE_TUNER_TOUCHPAD0_ID1_SIZE                                           (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_X0_OFFSET                                      (624u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_X0_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_Y0_OFFSET                                      (626u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_Y0_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_Z0_OFFSET                                      (628u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_Z0_SIZE                                        (2u)

#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ID0_OFFSET                                     (630u)
#define CY_CAPSENSE_TUNER_LINEARSLIDER0_ID0_SIZE                                       (2u)



#endif /* CYCFG_CAPSENSE_TUNER_REGMAP_H */

/* [] END OF FILE */
